### ISSUE TITLE
Effect Stacking on Disabled Effects

### ISSUE THREAD

**Issue by eccobold** [DFreds/dfreds-effects-panel#10]
**Describe the bug**
Now that effects are disabled on rightclick, I came to a situation where I had multiple disabled effects of the same type.

**To Reproduce**
1. Apply a effect let's say Cantrip - Light
2. Right click to disable
3. Apply effect again

**Expected behavior**
Activate the disabled Effect

**Screenshots**
![image](https://user-images.githubusercontent.com/71939920/150632728-cd52df12-be1f-457c-b92a-985ddf214a5c.png)

**Additional context**
It even adds another active effect on an already active effect, if you apply the CE with a spell. That may be a problem with midi-qol and not within your scope.

![image](https://user-images.githubusercontent.com/71939920/150632821-4d241271-2b66-442c-98cf-d9d65d12d15c.png)

**Comment by DFreds** [comment]
Yeah, neither midi nor CE checks if there is an existing disabled effect before applying a new one. It's probably out of scope to do so... if you prefer to delete effects, just do that instead.
