### ISSUE TITLE
Optional right click to delete

### ISSUE THREAD

**Issue by eccobold** [DFreds/dfreds-effects-panel#11]
**Is your feature request related to a problem? Please describe.**
Now that passive effects can be hidden, it's more secure to delete effects right away on a right click. 

**Describe the solution you'd like**
Have an option to go back to the old "right click to delete without prompt"

**Describe alternatives you've considered** <<-- Edited
Another solution or even another option your mod could supply could be
 right click on passive > disable/enable
 right click on temporary > delete
That way passives couldn't be deleted by mistake, temporary CE are the ones I want to delete anyways

**Additional context**
If you just disable, you accumulate a lot of disabled effects. And now that they are easly reactivated with a right click, they can now just as easily be reactivated by mistake without, for example, spending a spellslot to trigger them. I would love CE triggered by spells, to be gone forever until the spell is applied again.

**Comment by DFreds** [comment]
Yeah I kind of went back and forth on this... I wouldn't want to do have two separate behaviors depending on passive/temporary, as that would likely be confusing. Maybe I'll just add a setting to let you choose the right click behavior

**Comment by DarKDinDoN** [comment]
Agreed.

I think there are two use cases here:
- People using disable/enable effects: those certainly need "right-click" to **disable** effects
- People using adding/deleting effects: those need "right-click" to **delete** effects

Also agreed on the confirmation window. Might be a bit too much.
Or maybe it should be there only for passive effects? Because they are less often disabled/deleted.

**Comment by DFreds** [comment]
@DarKDinDoN agree with this. I think the UI could make it more clear, and then less confusing. I'll work on it

**Comment by DFreds** [comment]
Released in v1.3.0

**Comment by robnmeyer** [comment]
I'll throw my two cents in here - it will be nice if we didn't have to click on a confirmation when removing a temporary effect.  It sounds like some folks wanted this, but maybe we could have a configuration for this behavior in the config setting as well.....?  I really like the simple approach you had when this thing first came out.
