### ISSUE TITLE
Token marker of active buff/effect will not reappear if buff is activated after duration expires (PF1)

### ISSUE THREAD

**Issue by Ironxxx** [DFreds/dfreds-effects-panel#12]
**Describe the bug**
PF1 system, v80.7 (latest at time of writing)
Foundry v9 build 242
Mods used: Dfreds Effects Panel, Times Up, Simple Calendar

**To Reproduce**

Bug 1
1. Set up Buff using @item.level as attribute tied to Duration in the Buff setup
2. Enable a Buff on a token, in character sheet or on token with right click
3. Wait for time to run out or advance time with Simple Calendar
4. Buff ends and disappears from Effects Panel and is disabled on character
---- At this point the following error occurs:
```
Uncaught (in promise) Error: The key z4Su4BNgpw2YJLPd does not exist in the EmbeddedCollection Collection
[No packages detected]
    at Map.get (/home/foundry/foundryvtt/resources/app/common/utils/collection.mjs:106:13)
    at ServerDatabaseBackend._deleteEmbeddedDocuments (/home/foundry/foundryvtt/resources/app/dist/database/backend/server-backend.mjs:1:4618)
    at ServerDatabaseBackend.delete (/home/foundry/foundryvtt/resources/app/common/abstract/backend.mjs:214:31)
    at async Semaphore._try (/home/foundry/foundryvtt/resources/app/common/utils/semaphore.mjs:99:17) 
```

5. Try and reactivate the buff. The Buff will activate and change stats but it is not visible as a Token Marker or in Effects Panel

Bug 2
You can do the above in Combat, advancing time using the Combat Tracker. Done this way there is no error message, however the Buff is still active on the character sheet but disappears from the Effects Panel. The Buff re-appears on the Effects Panel if you disable then re-enable it.

**Expected behavior**
The Buff token marker should reappear when reactivated both on the token and in the effects panel when out of combat.
When using the combat tracker the Buff should disable itself on the character sheet when the duration ends.

**Screenshots**

**Additional context**

**Comment by DFreds** [comment]
This is likely an issue with times up as that is what is doing the deleting when time expires. Try asking or seeing if a similar issues exists there
