### ISSUE TITLE
[BUG] Effect detected as passive when it's not

### ISSUE THREAD

**Issue by DarKDinDoN** [DFreds/dfreds-effects-panel#14]
**Is your feature request related to a problem? Please describe.**
A passive in the effect statuses HUD created with CUB is detected as passive by this module.
The actor sheet shows the same effect as active, not passive.

**Describe the solution you'd like**
Remove the "passive" badge.

![image](https://user-images.githubusercontent.com/1687854/150839667-43d3502d-096e-4370-b8c1-24eb3c9b6cdb.png)

**Comment by DFreds** [comment]
Yep, thanks. I don't know why I didn't consider that, but I'll handle that case. I need to see what is different about those that they appear as temporary in the character sheet

**Comment by DFreds** [comment]
Fixed in v1.3.1

**Comment by DarKDinDoN** [comment]
Thx!
