### ISSUE TITLE
[FEATURE REQUEST] Compatibility with CUB journal notes

### ISSUE THREAD

**Issue by DarKDinDoN** [DFreds/dfreds-effects-panel#15]
**Is your feature request related to a problem? Please describe.**
When using CUB, we can link a journal note to the status effects conditions in the status effects HUD.

![image](https://user-images.githubusercontent.com/1687854/150839969-bbc19183-115c-4bdb-a704-9a4e88be5b81.png)

**Describe the solution you'd like**
It would be nice to have this module auto open this note if a user simply clicks on the icon and if the condition has a journal note linked.

CUB provides a method to get the details of a condition: `game.cub.getCondition('label')`

**Comment by DFreds** [comment]
CUB and Convenient Effects don't really play nicely with conditions because Foundry has no built-in way to add to the status effects. So adding support for this seems out of scope since you normally can't use them anyway
