### ISSUE TITLE
[FEATURE REQUEST] Hide effect details to players

### ISSUE THREAD

**Issue by DarKDinDoN** [DFreds/dfreds-effects-panel#16]
**Is your feature request related to a problem? Please describe.**
When hovering a status effect icon, the players and the GM get information about it.
The GM could prefer not to give such information, especially the time tracking badge.

![image](https://user-images.githubusercontent.com/1687854/150840603-c4b23174-b184-4c32-bdf7-b0d25ffc1733.png)

Like for example. If one of the PC is "poisoned", I don't necessary want my player to know for how many turns.

**Describe the solution you'd like**
Have an option to hide such information to the players

**Comment by DFreds** [comment]
Good call, didn't consider that. I can add a setting for that as well

**Comment by DFreds** [comment]
Added in v1.3.1

**Comment by DarKDinDoN** [comment]
Thx :)
