### ISSUE TITLE
Add in option to render the Effects' panel over other UI elements (like combat carousel etc.) Or add a way to customize the position of the effects' pennal.in different places, be able to move it.

### ISSUE THREAD

**Issue by SirAron111** [DFreds/dfreds-effects-panel#17]
**Is your feature request related to a problem? Please describe.**
Well I have a variety of UI elements display in the top, but sadly they overlap if not adjustable. The effects' panel is rendered on the bottom of them all, so I can't easily disable enable effects on the fly during combat with things like token bars and combat carousel getting in the way.

**Describe the solution you'd like**
As per the titles "Add in option to render the Effects' panel over other UI elements (like combat carousel etc.) Or add a way to customize the position of the effects' pennal.in different places, be able to move it."

**Any other thing**
That's about it. The only other option I would wish for would be to have add functional effects of Midi-qol, Token Magic  and the like to the commonly used dnd 5e status effects that are integrated by default. i mean it would be great if the grappled status would for example make the token unable to move, if the paralyzed one would make others auto crit them or if blind would make them unable to see anything, especially since I use the replace function of the effects for the token effect's sidebar. It would make it very convenient,

**Comment by DFreds** [comment]
Yes, there are a few open issues surrounding this. I think I will add functionality to allow you to drag it wherever you want, and then remember that location (similar to Token Action HUD). If that ends up being clunky, it'll probably turn into a setting instead

**Comment by DFreds** [comment]
The panel should now be drawn over base foundry apps. Since this was the original intention of this issue, I'll close it. Follow #4 for updates on moving it wherever
