### ISSUE TITLE
To remove, or not to remove

### ISSUE THREAD

**Issue by Ikabodo** [DFreds/dfreds-effects-panel#19]
I understand the complexity of making the choice between remove an effect and disabling it. But I suggest maybe re-adding the shift-right or something similar? 

I really liked the ability to both remove and disable.

**Comment by DFreds** [comment]
I hear ya. I might add a third option to the passive/temp configuration that would prompt a dialog asking which you'd want to do each time. Thoughts on that or other ideas?

The problem with shift + right click is that it would never, ever work with Firefox which is something I didn't know at the time. Firefox protects that combination so it always show the browser context menu.

**Comment by Ikabodo** [comment]
Maybe add in support for the shortcuts in v9? Then let the player choose? 
I don't know if that is possible though.

**Comment by rpganalyst** [comment]
I add my voice here because I was going to open the same suggestion thread. Maybe the prompted dialog could cointain a choice between Delete, Disable and Cancel.
I would prefer having right-click-->disable, Shift/Ctrl/Alt+right click-->delete to make the think flowing, but the choice dialog would work fine, I think.

Thank you for your wonderful module.

**Comment by DFreds** [comment]
> I add my voice here because I was going to open the same suggestion thread. Maybe the prompted dialog could cointain a choice between Delete, Disable and Cancel. I would prefer having right-click-->disable, Shift/Ctrl/Alt+right click-->delete to make the thing flowing, but the choice dialog would work fine, I think.
> 
> Thank you for your wonderful module.

That's a pretty good idea and should be an easy enough change. Thanks for the suggestion

**Comment by rpganalyst** [comment]
> > I add my voice here because I was going to open the same suggestion thread. Maybe the prompted dialog could cointain a choice between Delete, Disable and Cancel. I would prefer having right-click-->disable, Shift/Ctrl/Alt+right click-->delete to make the thing flowing, but the choice dialog would work fine, I think.
> > Thank you for your wonderful module.
> 
> That's a pretty good idea and should be an easy enough change. Thanks for the suggestion

My pleasure.

**Comment by DFreds** [comment]
Honestly, just lost track of this. I went ahead and added a dialog choice that allows either disabling or deleting. Released in 2.2.0
