### ISSUE TITLE
[FEATURE] Don't display passive effects

### ISSUE THREAD

**Issue by DarKDinDoN** [DFreds/dfreds-effects-panel#2]
**Is your feature request related to a problem? Please describe.**
Right now, this great module displays the passive effects.
The user can right-click and delete a passive effect.

**Describe the solution you'd like**
An option to not display passive effects (list can be quite long)

**Describe alternatives you've considered**
At least, do not disable/delete passive effect on right-click.

**Comment by DarKDinDoN** [comment]
Just saw that the following are also displayed and shouldn't:
- Disabled effects
- Suspended effects

**Comment by DFreds** [comment]
Good catches, thanks! I'll remove displaying suspended/disabled, and add a setting for showing passive or not.

**Comment by DFreds** [comment]
Fixed in v1.1.0
