### ISSUE TITLE
Option to allow players to view but not edit effects

### ISSUE THREAD

**Issue by MrPotatoZed** [DFreds/dfreds-effects-panel#22]
My players often don't have any idea what the symbols on their characters mean given the amount of effects that are flying around so having this to let them check is great. However, while I trust my players to not intentionally delete things by clicking on them they're pretty good at breaking things by mistake. It would be great to have a view permission that was "player-editing disabled" or some such so that players could view but not click on the status info. That way they could be kept from causing problems while still getting the benefit of the effects panel.

**Comment by DFreds** [comment]
Sure, that is possible. But you know that they could just go to the effects tab on their character sheet and do whatever they wanted, right?

**Comment by MrPotatoZed** [comment]
Absolutely, but that would require them to actually poke around their character sheets (unlikely for my players at least, bless their hearts) and there's no risk of accidental right clicking on the wrong part of the screen taking out stuff.  I'm not worried about intentional messing about but my folks have trouble remembering basic stuff about how foundry works from week to week so it's just a thought to prevent issues from folks like them. It is at most a minor QOL request and no worries if you think it's not a big enough deal to justify the effort to make changes. Just wanted to flag the potential use case. Thanks for looking at it.

**Comment by DFreds** [comment]
> my folks have trouble remembering basic stuff about how foundry works from week to week 

I feel this in my soul.

I'll probably add it.

**Comment by DFreds** [comment]
Lost track of this, but ultimately it doesn't really stop anybody from doing this so I won't be adding it
