### ISSUE TITLE
Request: Single Right-Click to Remove (without confirmation)

### ISSUE THREAD

**Issue by pesky-wobbit** [DFreds/dfreds-effects-panel#23]
I love having the right-click to remove an effect and especially giving this to my players! Letting them stand up from prone or give themselves cover gets them involved and speeds things up tremendously.

Why have the confirmation? We always say yes.

In the unlikely event of an accidental click, the effect can be reapplied.

**Comment by DFreds** [comment]
If only you had a way to delete immediately without a prompt... HMMMM.

It's in the settings.

**Comment by pesky-wobbit** [comment]
I went over the settings with a fine tooth comb. Unfortunately I was
looking at CE.
Thank you!
