### ISSUE TITLE
Posible bug between LightsHud+ATE and DF effects panel

### ISSUE THREAD

**Issue by Fridan99** [DFreds/dfreds-effects-panel#25]
**Describe the bug**
There seems to be some kind of problem between the DF Panel effect and LightsHUD+ATE. Description of the problem: https://github.com/p4535992/foundryvtt-lights-hud-ate/issues/9

It appears that there may be an interaction between the two modules. With a DAE effect (in this case Radiant Soul feature), an actor auto activates the effect simply by right clicking on his token. I have found that this DAE autorun is solved by disabling either LightsHud+ATE or the DF Effects Panel. So I think there is some conflict between both modules. 

Download the actor .json
https://easyupload.io/kmv6jg

https://user-images.githubusercontent.com/86131373/173241201-a1277996-cd4b-4dd1-83d0-72df78cd2fe9.mp4

**To Reproduce**

**Expected behavior**
in the thread 

**Screenshots**
in the thread 

**Additional context**
in the thread hung

**Comment by Fridan99** [comment]
The author of LightsHUD+ATE has updated to 0.11.22 the bug has been "partially" fixed.

It seems that the DAE effect is no longer auto-executing. But there is still some kind of error. Even if the effect itself does not autorun, the icon effect appears in the DF Effects Panel as if it had been executed. Strange.

https://user-images.githubusercontent.com/86131373/173242366-a2ad9412-7d8f-4e6a-bc05-b92c629af56a.mp4

**Comment by DFreds** [comment]
You can see that the Radiant Soul effect has a "Disabled" flag. The effects panel shows all effects currently on a character, even the disabled ones. You can turn that off in the settings

**Comment by Fridan99** [comment]
The problem has been solved by the LightsHUD+ATE 0.11.24 update.
