### ISSUE TITLE
[Feature Request] New Settings Options

### ISSUE THREAD

**Issue by SosukeAizen** [DFreds/dfreds-effects-panel#27]
I have recently run into an issue where I have a passive effect on a token and I want to display it on the token, using the force display option added by DAE or by using a Macro. This changes the effect into a temporary effect without a duration. 

Having setup the currents option with different right click behaviours, delete for temporary effects and disable for passive effects, I'm running into an issue where I need the effect to remain on the token and is also displayed on the token while also being able to easily disable it. 

The specific effects I'm working with are flanking, half cover, and three-quarters cover. 

I posted a question into the foundry discord in an attempt to get a passive effect that displayed on the token but was eventually directed to submit a feature request for a new option - Shift Right Click Behaviour.

That way people can easily disable and delete effects using the Effects Panel without having to go into the sheet.

**Comment by DFreds** [comment]
I guess I'm a little confused on this. You can change the behavior for passive or active effects to be disabled/deleted on right click. Is this asking for both behavior to be available based on if the shift modifier is used?
