### ISSUE TITLE
[Feature Request] Toggleable lock position in settings

### ISSUE THREAD

**Issue by marceloabner** [DFreds/dfreds-effects-panel#28]
A good feature would be a toggle/checkbox in configurations that lock the position of the effects bar. Whenever an effect is double-clicked to edit its properties, the bar keeps moving, which it is weird and annoying.

**Comment by DFreds** [comment]
Interesting. I'll look into it or into a way to make the drag not happen immediately

**Comment by DFreds** [comment]
Drag now only occurs after holding down for a second
