### ISSUE TITLE
[Feature Request] Shift click to open effect AE dialogue

### ISSUE THREAD

**Issue by roguedevjake** [DFreds/dfreds-effects-panel#29]
Shift click to open the active effect dialogue for the item (ideally  with initial focus set to the duration tab) 

Extempore effects enables this for Pathfinder 2e effects and it is exceptionally useful for when durations need to be re applied after effects are accidentally removed, or if something impacts the duration of an effect initially.

**Comment by DFreds** [comment]
You can open it by double clicking the icon. v2.0.1 fixes an issue where the ability to drag the panel around was interfering with this behavior
