### ISSUE TITLE
[BUG] 1 turn duration is displayed as "Unlimited"

### ISSUE THREAD

**Issue by DarKDinDoN** [DFreds/dfreds-effects-panel#3]
**Describe the bug**
The effect panel displays 1 turn duration as "Unlimited".

**To Reproduce**
1. Create an active effect with a duration of 1 turn
2. Activate this on a PC
3. Check the duration in the effect panel for said effect

**Expected behavior**
Display the number of turns?

**Comment by DFreds** [comment]
Added this in v1.1.0 as well. I think I need a better way to handle displaying durations, but this should work for now.

**Comment by DarKDinDoN** [comment]
@DFreds And some localization too :)
