### ISSUE TITLE
Remove HTML tags from tooltips

### ISSUE THREAD

**Issue by benbarbour** [DFreds/dfreds-effects-panel#30]
**Describe the bug**
Tooltips shouldn't show HTML tags

**Expected behavior**
I'm not sure if really long descriptions should be truncated, but they should at very least have tags removed.

**Screenshots**
![image](https://user-images.githubusercontent.com/487715/192079058-c3a28b84-75f2-4c92-a0e2-beb3450ebf08.png)

**Comment by DFreds** [comment]
Both might be a good option. Thanks for the heads up

**Comment by PRO-BROS** [comment]
I will definitely do this in my [site](https://prhocoding.com/)

**Comment by DFreds** [comment]
Fixed in v2.0.3
