### ISSUE TITLE
[Feature Request] create effect from Chat Card (extempore effects)

### ISSUE THREAD

**Issue by roguedevjake** [DFreds/dfreds-effects-panel#31]
There is a pathfinder 2e module named Extempore Effects that allows the creation of effects from chat cards, assignment of descriptive text and if there is a numerical duration sets it. 

This is very useful when it comes to tracking monster/npc effects as well as spells that have durations but no effect attached.

**Describe the solution you'd like**
To be able to right click on a chat card and select "create effect", this will then create a dynamic effect on the selected token/tokens.
This will also set:
- the image of the effect to any image linked to the chat card, defaulting to the image of the chat card poster if there isn't one.
- the description of the effect to the contents of the chat card (for easy reference)
- the duration of the effect to the duration listed in the chat card (if there is one) 

**Additional context**
[Link to Extempore Effect's Git](https://github.com/shemetz/pf2e-extempore-effects)[
Link to image showing it in effect](https://github.com/shemetz/pf2e-extempore-effects/blob/master/metadata/ee_demo_1.gif)

**Comment by DFreds** [comment]
This isn't really related to this module, but might make a good separate module
