### ISSUE TITLE
BUG: Inactive Effects are always shown

### ISSUE THREAD

**Issue by GambetTV** [DFreds/dfreds-effects-panel#34]
In version 2.0.4 of this module, and Foundry v10.291 and DnD5e 2.1.4, Inactive Effects are always shown now, even if "Show Disabled Effects" is unchecked. Checking this option simply grays it out.

**Comment by DFreds** [comment]
Thanks for the report. Just changed around how this worked, so I probably broke it. Will fix

**Comment by DFreds** [comment]
Fixed in v2.0.5

**Comment by DFreds** [comment]
Make that v2.1.0
