### ISSUE TITLE
Effect bar position wrong when A/V functionality right docked

### ISSUE THREAD

**Issue by STBaf** [DFreds/dfreds-effects-panel#36]
**Description**
When using Foundrys A/V functionality and with the A/V Icon or Camera space docked to the right sight the whole right sidebar is moved out of the way to make the extra-space for the A/V dock on the right side by moving the menu some pixels to the left.
Unfortunately, the location of the Active Effects are not moved, too, so you end up having Effect status icons "hanging around" in the middle of the right menu bar.

**To Reproduce**
1. Enter world, active AV functionality
2. Change docking of the v10 new A/V bar to "Right".
3. (add/)Select actor with effects to any scene, see the Effects Panel not moving with the right sidebar menu. Instead find the effect icons in the middle of the right sidebar menu on the location where they would be correct if there wasn't a additional A/V panel added to the right side.

**Expected behavior**
Effect panel should move same space to left like the right sidebar menus does when setting the A/V panel to the right position docking.

**Comment by DFreds** [comment]
Fixed in v2.1.0

**Comment by tehguitarist** [comment]
@DFreds, unfortunately, now it's off when A/V is docked to the left ha.
![Screenshot 2023-01-31 at 6 17 27 pm](https://user-images.githubusercontent.com/28495826/215692467-7cadcda3-c00f-45c9-9f7c-5aba9f747ee6.png)

**Comment by DFreds** [comment]
Whoops! Thanks, will fix

**Comment by DFreds** [comment]
Should be good in v2.1.1... Hopefully
