### ISSUE TITLE
Resizable effects panel icons and text.

### ISSUE THREAD

**Issue by ManifestCuriosity** [DFreds/dfreds-effects-panel#37]
I'd like the following options for usability: 

- Ability to increase the size of the condition icons in the effects panel.
- Ability to increase the font size of the condition description when hovering over a condition in the effects panel.

On my screen the details are difficult to read. A longer effect description is also overflowing the container behind the text,

Thank you!

![image](https://user-images.githubusercontent.com/126837346/222608017-8936d97f-30b4-4c3b-8ea4-1ccfad426066.png)

**Comment by DFreds** [comment]
Good call, it is kind of small. I'll see what I can do despite truly hating CSS 😆

**Comment by DFreds** [comment]
I resized everything in v2.1.4
