### ISSUE TITLE
Effects panel hides behind sidebar

### ISSUE THREAD

**Issue by fortypercenttitanium** [DFreds/dfreds-effects-panel#38]
**Describe the bug**
The effects panel is hidden behind the sidebar, rendering is nearly unusable.

Foundry v10 build 291
Windows 11
DFreds Effects Panel 2.1.3

**To Reproduce**
1. Open a new or existing world
2. Apply an effect to an actor
3. Observe the actor's effect panel hiding like such:

**Expected behavior**
The effects panel should float to the left of the sidebar

**Screenshots**
![image](https://user-images.githubusercontent.com/61510135/225124982-4eb14cff-271c-4bed-ab2a-171e41ba8358.png)

![image](https://user-images.githubusercontent.com/61510135/225125012-e8936731-15f2-441d-a8e7-d36fdb0c630e.png)

**Additional context**
I will be submitting a PR soon to fix the issue

**Comment by DFreds** [comment]
Hmmm... I'm not seeing this happen at all. Did you take any other steps to reproduce it?

**Comment by fortypercenttitanium** [comment]
> Hmmm... I'm not seeing this happen at all. Did you take any other steps to reproduce it?

Nope, I'm actually new to foundry altogether. New world, new everything. No other modules installed. Using Pathfinder 2e. Tried with both electron app and in browser (Chrome).

Any other steps you'd recommend trying?

**Comment by DFreds** [comment]
Ah, well this module isn't compatible with Pathfinder 2e because Pathfinder 2e already has its own effects panel. That's where this whole module came from, taking that idea and extending it to other systems. Did you only try pf2e?

**Comment by fortypercenttitanium** [comment]
> Ah, well this module isn't compatible with Pathfinder 2e because Pathfinder 2e already has its own effects panel. That's where this whole module came from, taking that idea and extending it to other systems. Did you only try pf2e?

I feel like a doofus now. I will try it later tonight.

I got your module from a list of really good ones on Reddit, and while I was playing in a previous campaign I thought, I love this tray! I had no idea it was native to that game system.

Thanks for your help.

**Comment by DFreds** [comment]
No problem! I appreciate the initiative. Please fix other bugs you find 😆 

But let me know if somehow it persists, because I don't think your fix actually breaks anything else.
