### ISSUE TITLE
[SUGGESTION] - Add visual difference between passive and active effects

### ISSUE THREAD

**Issue by Ikabodo** [DFreds/dfreds-effects-panel#40]
**Is your feature request related to a problem? Please describe.**
Currently it can be hard to visually differentiate between active and passive effects. 

**Describe the solution you'd like**
Simply add `border-radius:5px` to passive effect.
![image](https://user-images.githubusercontent.com/7766890/233606690-e0f780be-5b60-4eb7-a046-06f59a1e09ac.png)

or even more if you want it to be even clearer.
![image](https://user-images.githubusercontent.com/7766890/233608006-a88dcada-225a-4200-a4a0-f09a7e061c69.png)

**Describe alternatives you've considered**
An alternative is to add a passive/active class to the css so people can customize it themselves.

**Comment by Ikabodo** [comment]
I did a small custom css-modifer that did the above if anyone is interested.
Might not work on all browsers.

```css
.icon:has(.unlimited) {
	border-radius:50px;
	filter:grayscale(0.5) !important;
}
```

**Comment by DFreds** [comment]
I like this idea. Will add!

**Comment by DFreds** [comment]
Added in v2.2.0
