### ISSUE TITLE
Support journal links

### ISSUE THREAD

**Issue by 9ryex5** [DFreds/dfreds-effects-panel#41]
Can you add support for journal links?
![image](https://user-images.githubusercontent.com/43207603/234551111-d41996b2-71ec-4a89-a545-004a02d23cf6.png)

Like [Visual Active Effects](https://foundryvtt.com/packages/visual-active-effects) does
![image](https://user-images.githubusercontent.com/43207603/234552334-bfdc7a1a-aa7f-48a2-bea7-f500f9ed786f.png)

**Comment by DFreds** [comment]
Added in v2.2.1
