### ISSUE TITLE
Please add ability to add custom descriptions to conditions for non 5e systems.

### ISSUE THREAD

**Issue by Oryan77** [DFreds/dfreds-effects-panel#42]
Being able to hover over the icon to see the name & description of a condition the way you can in a 5e system if using DFreds Convenient Effects would be great.

Perhaps an option to load the list of existing conditions with a blank box to enter our own condition "notes" or full descriptions would be nice if possible. Then when hovering over the icon, it will show the added description.

**Comment by DFreds** [comment]
Hover over which icon exactly? The ones on the token status effects that appear when right clicking? Sorry, just a bit confused. 

You can of course duplicate any effect and change the description in the custom effect that appears. As long as you keep the same name, CE will always choose the custom one over the existing one.

**Comment by Oryan77** [comment]
I'm sorry, I should have specified that I'm using the 3.5e Game System and Convenient Effects doesn't load for that system.

I thought maybe Effects Panel could just allow for generic editing of conditions that are loaded. Or a Convenient Effects for 3.5e would also be nice.

Specifically, I'm referring to hovering over the icons that appear top right (left of the chat window). I was under the impression that hovering over them in 5e displays their description text. So I was hoping for that in the 3.5e system.
![image](https://github.com/DFreds/dfreds-effects-panel/assets/49130820/a0256212-d8df-48db-945e-343993a313f2)

**Comment by DFreds** [comment]
Oh, gotcha. So the description field used to be an addition that Convenient Effects made, but now it is part of native Foundry v11. Effects Panel will choose the native field over the CE field (and CE removed support for its v11 version). So I think the solution here is to wait for 3.5e to update to v11 and they can either add descriptions themselves or you can add them after in the effect editor.
