### ISSUE TITLE
foundry hud weblate

### ISSUE THREAD

**Issue by eunaumtenhoid** [DFreds/dfreds-effects-panel#43]
hi, is it possible to add your mods to foundry hud weblate for us to translate or update the translation faster? https://weblate.foundryvtt-hub.com/

**Comment by DFreds** [comment]
Cool tool, wasn't aware of it. I'll need to set this package up for the initial English translation, and then I'll submit a request there.

**Comment by DFreds** [comment]
Localized and submitted request. Hopefully it should appear there soon. Thanks!
