### ISSUE TITLE
Effects Display Description when Manually added, not when added via combat roll

### ISSUE THREAD

**Issue by MagicOriole** [DFreds/dfreds-effects-panel#46]
Disabled all mods except DFreds effects Panel

![image](https://github.com/DFreds/dfreds-effects-panel/assets/96490347/87501483-10b9-44c8-abb1-0acf524e4d48)

**Comment by DFreds** [comment]
Sorry for the late response on this (had a bit of a hiatus), was this effect being applied by midi or no?

**Comment by DFreds** [comment]
No response, can't reproduce
