### ISSUE TITLE
Misleading information on how controls works

### ISSUE THREAD

**Issue by Chargoal** [DFreds/dfreds-effects-panel#48]
Not technically a bug. 
Controls are written on the main github page and are such:
"• You can double click the icon to immediately open the configuration sheet for that effect.
• You can right click the icon to immediately disable the effect.
• You can shift + right click the icon to be prompted to delete the effect."

However these controls are not what module actually offers and there is no way to make them such. What actually is offered in the module itself (see impeded screenshot):
"• You can double click the icon to immediately open the configuration sheet for that effect." - That's still true
"• You can right click the icon to immediately disable the effect." - It's configurable, but if set to "Disable" and not "Dialog" which is how it should have been working - then there is no way to delete an effect via Effects Panel.
"• You can shift + right click the icon to be prompted to delete the effect." - Not implemented at all. You can only delete by Right Click but only if it's configured that way.

I don't know whether it's just a problem of not updating the main page or the features of the module being lost throughout the versions, but either way it's very misleading and should probably be fixed either in the module itself (best, but harder way) or on the page, so that the people are not mislead (easier way).
Personally for me, I was lured by such crisp controls and were sad to see they are not actually implemented in the module.

![DFreds EP controls](https://github.com/DFreds/dfreds-effects-panel/assets/62655322/03480e7b-9800-4768-92ab-b8e0a66f712e)

**Comment by DFreds** [comment]
Yeah, just forgot to update the readme. Sorry about that, will update them.
