### ISSUE TITLE
Right-click remove for GMs only

### ISSUE THREAD

**Issue by samgrieve** [DFreds/dfreds-effects-panel#5]
Could we have a setting to lock the right-click to remove an effect function so that only GMs can do this? Have had two users so far right click the panel by mistake and remove effects

**Comment by dmaneyapanda** [comment]
I'd like for the removal to require a confirmation too, or some keybinding.  It's just too easy to accidentally right click on something and lose it, even as (maybe even especially as) a GM.  

Perhaps this is less important if #6  is implemented to filter out all the permanent effects that are very difficult to add back in again mid-game.

**Comment by DFreds** [comment]
Yeah, I think I'll add in a key binding to delete and otherwise disable. Look for it in the next release

**Comment by DFreds** [comment]
I added a view permission based setting as well as a confirmation dialog. The disabling can be tracked in #7
