### ISSUE TITLE
Hide passive effects

### ISSUE THREAD

**Issue by eccobold** [DFreds/dfreds-effects-panel#6]
**Is your feature request related to a problem? Please describe.**
Adding convenient effects is super easy. It is also super easy to delete them. And unfortunately, it's not only easy to delete them, but also all the other effects. By that I mean passive effects like those created by the equipment I wear or by certain class features. If something like this is accidentally deleted, the only way to restore the effects is to create them again or to restore the character completely, e.g. by importing a ddb.

**Describe the solution you'd like**
I would be excited about an option to hide certain effects from the panel altogether. After all, many effects are not displayed on the token. As a rule, they should be the same.

**Describe alternatives you've considered**
I'm sorry, I can't think of anything, but I'm open to suggestions.

**Additional context**
For example: Ring of Protection gives +1 AC and +1 to Saves as a passive effect.

best thanks

**Comment by dmaneyapanda** [comment]
Seconded!

**Comment by eccobold** [comment]
> 

I see that you already made a setting for this. then I look forward to the next release all the more!

**Comment by GhostwheelX** [comment]
Thirded. I would also like the option not to show effects that do not have a duration (only to show temporary effects) for much the same reason.

**Comment by DFreds** [comment]
@GhostwheelX that sounds like a separate request. Feel free to make a new issue for it. Otherwise, v1.1.0 implements the original ask
