### ISSUE TITLE
Short cut to suspend with visual clue

### ISSUE THREAD

**Issue by Ikabodo** [DFreds/dfreds-effects-panel#7]
**Is your feature request related to a problem? Please describe.**
Some effects are toggled quite often, and usually that is handled by conventient effects. But some effect such as that from armors and other things would be good to be able to suspend.

**Describe the solution you'd like**
A simple way to enable and disable it, like shift-click or something. And a simple visual clue on the icon if it is suspended or not.

**Describe alternatives you've considered**
A context menu to change it, but that seems overly complicated considering you can open the setting and change it there.

**Comment by DFreds** [comment]
Yep, good idea. I'm planning on making right click disable, shift click delete (or other key binding), and allowing an option to show disabled effects with some kind of grey filter or something. It'll be out in the next release

**Comment by DFreds** [comment]
Fixed in v1.2.0
